FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /src

COPY ["Pacientes.Api.csproj", "./"]

RUN dotnet restore "Pacientes.Api.csproj"

COPY . .

RUN dotnet publish "Pacientes.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final

WORKDIR /app

COPY --from=build /app/publish .

EXPOSE 8080

ENTRYPOINT ["dotnet", "Pacientes.Api.dll"]